"""
modules/dispatch_schemas.py
----------------------------
Pydantic models for Service 4: Dispatch Brainstorm.

After Service 3 generates an outreach draft, the team can open a
brainstorm session to plan and refine their outreach strategy through
an AI-powered conversation.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


# ── Shared ────────────────────────────────────────────────────────────

class ChatMessage(BaseModel):
    """A single message in the brainstorm conversation."""
    role: str = Field(
        ...,
        description="Message author: 'user', 'assistant', or 'system'.",
    )
    content: str = Field(
        ...,
        description="Message body.",
    )


# ── Create Session ────────────────────────────────────────────────────

class DispatchCreateRequest(BaseModel):
    """
    Payload for POST /api/v1/dispatch/create.

    Sent by the frontend after the outreach draft (Service 3) is generated.
    Captures all context needed to seed the brainstorm conversation.
    """

    entity_id: str = Field(
        ...,
        description="UUID of the target entity from the `entities` table.",
    )
    entity_name: str = Field(
        ...,
        min_length=1,
        description="Display name of the entity (hospital/NGO).",
        examples=["District Hospital Kakinada"],
    )
    pilot_description: str = Field(
        ...,
        min_length=10,
        description="Description of the maternal health pilot programme.",
        examples=["AI-driven maternal nutrition pilot for rural mothers"],
    )
    channel: str = Field(
        ...,
        description="Outreach channel used (email, whatsapp, phone_script, etc.).",
        examples=["email"],
    )
    outreach_subject: str = Field(
        default="",
        description="Subject line from the outreach draft (empty for non-email channels).",
    )
    outreach_body: str = Field(
        ...,
        min_length=10,
        description="Full body/content of the outreach draft generated by Service 3.",
    )


class DispatchCreateResponse(BaseModel):
    """Returned after a brainstorm session is created."""
    session_id: str = Field(..., description="UUID of the new dispatch session.")
    seed_message: str = Field(
        ...,
        description="AI-generated opening message summarising the context and inviting brainstorming.",
    )


# ── Chat ──────────────────────────────────────────────────────────────

class DispatchChatRequest(BaseModel):
    """Payload for POST /api/v1/dispatch/{session_id}/chat."""
    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The user's brainstorm message.",
    )


class DispatchChatResponse(BaseModel):
    """AI reply to a brainstorm message."""
    session_id: str = Field(..., description="Session this reply belongs to.")
    reply: str = Field(..., description="GPT-4o brainstorm reply.")


# ── Get Session (Resume) ─────────────────────────────────────────────

class DispatchSessionResponse(BaseModel):
    """Full session payload returned for GET /dispatch/{session_id}."""
    session_id: str
    entity_id: str
    entity_name: str
    pilot_description: str
    channel: str
    outreach_draft: dict = Field(..., description="Original outreach draft context.")
    messages: List[ChatMessage] = Field(
        default_factory=list,
        description="Full conversation history.",
    )
    created_at: str
    updated_at: str
